### ISSUE TITLE
COPX Master issue

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#496]
We have multiple COPX issues open atm - all of them being stale atm.
Merging it into one issue, so we can reduce the amount of clutter in our issue board.

#458 
@krislarsen Check if all COPX related to OGDIT is in there. Looked to me that Møre APP> ENSV is missing for OGDIT COPX
@Sanderli25 No COPX to OGDIT defined in GNG. Will look into this.

---
#303 
@krislarsen 
Looks like Polaris gets the DCT IPMOD COPX that are supposed to go to ENGM_W_APP
---
#290 
@krislarsen 
This is a combined issue of #208 , #220 & #231 
All of theese issue is due to incorrect COPXes. I believe many of the added "dummy" COPX lines made more trouble than solutions. I've removed all unnessesary COPX now and need now a lot of help to check following things:

- [ ] ENBR Dep via S5 and S8 gets RFL
- [ ] ENBR Arr via S8 is handed over to S9 with no descend
- [ ] ENBR arrr via S5 & S6 is getting XFL FL320
- [ ] ENSV can give COPX TNO, AAL and LOKSA without bypassing COPX

Phase 2:

- [ ] TIPAN + BAVTA COPX

Any missing COPX according to SOP/LoA between ENBD/ENSV/ENOS AoR shall be reported here.

@Adrian2k 
ENSV_CTR via S9 to ENOR_S_CTR via S8 dep ENBR seems to still trigger XFL F310

---
#287 
@marud94 
SOP says BR APP can route flights to GUNPA and VALDI if in their flightplans without prior coordination. When selecting VALDI in the direct list it says it will send COPX to ACC.

@krislarsen 
Both VALDI and GUNPA were added in GNG. Have adjusted Sortorder and moved the respective point from COPX FIX to Fixafter. Testing is nessesary.

@marud94 
Tried testing on sweatbox, ended up with it sending COPX for REKLI as well. Need more testing, preferably on live network.

**Comment by Adrian2k** [comment]
Leaving this as unassigned until someone actually will start looking into this.

**Comment by Sanderli25** [comment]
OGDIT Added
![image](https://github.com/user-attachments/assets/6bb70f29-7388-45ea-a825-2b05041a0b57)

**Comment by janfelhut04** [comment]
https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/issues/376

Climb altitude gives cruise an not FL190 which is max permittable for APP (No direct given) From APP to ENBD

**Comment by marud94** [comment]
@janfelhut04 Do you have a screenshot with aircraft position in relation to TMA, the route and the altitude? Easier for troubleshooting that way

**Comment by Adrian2k** [comment]
Its all AMIMO departures, reported by multiple controllers now

Also all BARVI inbounds RWY18 has CFL 110 when its supposed to be 190

**Comment by Atriusftw** [comment]
Missing suggested altitude/level in Helgeland TMA (ENBN_APP)
![image](https://github.com/user-attachments/assets/f26a1a2b-0c45-4101-96e5-2e531a651c36)

**Comment by Atriusftw** [comment]
COPX suggests FL330 (cruise) for flights to Sweden, when ESOS is online and Polaris offline. Should be 290?

![image](https://github.com/user-attachments/assets/e6595389-bb53-438c-8a76-c60ba65445e2)

**Comment by marud94** [comment]
@Atriusftw in the future, please include a screenshot of the tag when it happens, makes it easier to troubleshoot for us.

It looks like he just got airborne, what was his altitude? It’s pretty normal for the CJI and altitude to be wrong if he hasn’t actually entered the TMA. Also did it correct itself at any point, for example above FL100?

**Comment by Atriusftw** [comment]
> @Atriusftw in the future, please include a screenshot of the tag when it happens, makes it easier to troubleshoot for us.
> 
> It looks like he just got airborne, what was his altitude? It’s pretty normal for the CJI and altitude to be wrong if he hasn’t actually entered the TMA. Also did it correct itself at any point, for example above FL100?

Yup, shortly after rotate. I estimate that the aircraft was around 1100ft or something.
Did not try after FL100, but it did not change when trying around 6000ft here. Have experienced this with other aircraft as well above ~4000ft tho.

**Comment by marud94** [comment]
@Atriusftw ES handles COPX weird and different all of the time. I generally notice that it fixes itself around FL100 if something is wrong. Doing anything in the tag immediately after rotate and expecting COPX to be correct is not the wisest as most checks for COPX and such will fail. There is nothing wrong in doing these things so early if you do it by knowledge of SOP though, and not by COPX.

**Comment by Atriusftw** [comment]
> @Atriusftw ES handles COPX weird and different all of the time. I generally notice that it fixes itself around FL100 if something is wrong. Doing anything in the tag immediately after rotate and expecting COPX to be correct is not the wisest as most checks for COPX and such will fail. There is nothing wrong in doing these things so early if you do it by knowledge of SOP though, and not by COPX.

I simply didn't know about this quirk, atleast expected it to be "loaded" before aircraft reaches initial climb.

**Comment by krislarsen** [comment]
> COPX suggests FL330 (cruise) for flights to Sweden, when ESOS is online and Polaris offline. Should be 290? Also CJI is advisory.
> 
> ![image](https://private-user-images.githubusercontent.com/1478937/396563067-e6595389-bb53-438c-8a76-c60ba65445e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTM3NzksIm5iZiI6MTczNDU1MzQ3OSwicGF0aCI6Ii8xNDc4OTM3LzM5NjU2MzA2Ny1lNjU5NTM4OS1iYjUzLTQzOGMtOGE3Ni1jNjBiYTY1NDQ1ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMjAyNDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ1YzcxMjY1MGFhNmFiMzJlYTI5YWFlMmQxNzcwOGQzMWMwNzJkZTc1M2VhMWQyNTQ4NDRmNGYwZTA0OGYzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.c3jYDRV8ZtVScMoPApFrjoTjRFaaHnxPo5xzPBsCyGU)

Adjusted with some new lines that hopefully will work better. Please test this with next sectorfile update or dev and let me know the outcome

**Comment by krislarsen** [comment]
> Missing suggested altitude/level in Helgeland TMA (ENBN_APP)
> 
> ![image](https://private-user-images.githubusercontent.com/1478937/396292295-f26a1a2b-0c45-4101-96e5-2e531a651c36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTM3NzksIm5iZiI6MTczNDU1MzQ3OSwicGF0aCI6Ii8xNDc4OTM3LzM5NjI5MjI5NS1mMjZhMWEyYi0wYzQ1LTQxMDEtOTZlNS0yZTUzMWE2NTFjMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMjAyNDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2YyNzhlM2FkNGQ4ODk2NDA0ODRhNjAzOGRmZjBmOTMzZjBjYTNlNDgyZDQ2NjYwNTI3NTVkZWNkMDU4YmY0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.y0YWoI96LUj19RZcuT3D462zf9ULcBfMTZQOnobxATE)

All departure agreeements were missing. Added a line to each SID + a general agreement for climb to FL140 from all AD within Helgeland TMA.

![image](https://github.com/user-attachments/assets/47fe0914-4d1b-45ab-a595-677797b116bc)

**Comment by krislarsen** [comment]
#303 
Reconfigured a new method to see if we get a better outcome. COPX FIX and FIX AFTER is all clear in the lines. COPX should only be looking at name, witch is IPMOD

**Comment by krislarsen** [comment]
> ![Skjermbilde 2024-12-14 171947](https://private-user-images.githubusercontent.com/126728914/395798485-27343f13-a6c6-416e-ad19-b2e8c769c17e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTM2OTEsIm5iZiI6MTczNDU1MzM5MSwicGF0aCI6Ii8xMjY3Mjg5MTQvMzk1Nzk4NDg1LTI3MzQzZjEzLWE2YzYtNDE2ZS1hZDE5LWIyZThjNzY5YzE3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQyMDIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjAyMDg0MWI5ZjZhNDkyYWVjNDhkNDc3ZjZmM2EyNDZkYjMzYjM4MDA1YjU3YjEzZTZlYzNhNTJjMTRkZjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vHAE_u4ordCenpGb_4xJNLlFH2SqO6zPv4T7-xnEbPY) #376
> 
> Climb altitude gives cruise an not FL190 which is max permittable for APP (No direct given) From APP to ENBD

+ #376 

Old waypoint in GNG witch made it difficult to find the rule for ES. Should be working now. Did anything else work @janfelhut04 ?

**Comment by Lassssse** [comment]
No image. But departures ENBR, ENZV and ENHD from sector 13 to 14 and vice versa are COPX RFL, instead of FL 250 as stated in agreement. (Reported with ENSV_N and ENSV online)
